project:
  type: book
  output-dir: docs
  
lang: hu-HU
language: _language-hu.yml

filters:
  - pandoc-quotes.lua

book:
  title: "Az orvosi megismerés módszertana (és az orvosi kutatások kritikus értékelése)"
  author:
    - name:
        given: Tamás
        family: Ferenci
        literal: Ferenci Tamás
      email: tamas.ferenci@medstat.hu
      url: https://www.medstat.hu/
  date: today
  date-format: "YYYY. MMMM D."
  downloads: [pdf, epub]
  sharing: [twitter, facebook, linkedin]
  cover-image: orvosi-megismeres-modszertana-cover.jpg
  cover-image-alt: "Érvágás illusztrációja középkori kódexben"
  image: orvosi-megismeres-modszertana-cover.jpg
  image-alt: "Érvágás illusztrációja középkori kódexben"
  open-graph: true
  twitter-card: true
  site-url: https://ferenci-tamas.github.io/orvosi-megismeres-modszertana
  repo-url: https://github.com/ferenci-tamas/orvosi-megismeres-modszertana
  repo-actions: [edit, source, issue]
  description: "Mind érdeklődőknek, mind orvosoknak, egészségügyi szakdolgozóknak szóló összefoglaló, mely igyekszik közérthetően bemutatni az empirikus orvosi kutatások módszertani alapjait, hangsúlyosan kitérve a félreértésekre és félrevezetésekre is, hogy ez alapján könnyebb legyen az ilyen vizsgálatokat értelmezni, értékelni és kritikusan értékelni."
  language: hu-HU
  output-file: "ferenci-tamas-orvosi-megismeres-modszertana"
  chapters:
    - index.qmd
    - bevezetes.qmd
    - alapok-confounding.qmd
    - megfigyeles-kiserlet.qmd
    - megfigyeleses-vizsgalatok.qmd
    - veletlen-ingadozas.qmd
    - vegpont.qmd

format:
  html:
    theme: cosmo
    include-after-body:
      text: |
        <script type="text/javascript">
        var sc_project=12422840; 
        var sc_invisible=1; 
        var sc_security="d32cce24"; 
        </script>
        <script type="text/javascript"
        src="https://www.statcounter.com/counter/counter.js"
        async></script>
        <noscript><div class="statcounter"><a title="ingyenes
        webstatisztika" href="https://www.statcounter.hu/"
        target="_blank"><img class="statcounter"
        src="https://c.statcounter.com/12422840/0/d32cce24/1/"
        alt="ingyenes webstatisztika"
        referrerPolicy="no-referrer-when-downgrade"></a></div></noscript>
  pdf:
    documentclass: scrreprt
    links-as-notes: true
  epub:
    cover-image: orvosi-megismeres-modszertana-cover.jpg